### ISSUE TITLE
Tin AIOTs

### ISSUE THREAD

**Issue by spurcy** [Luligabi1/BasicAIOTs#3]
So when ever I try to repair a tin aiot my game crashes. Could you please fix this?

**Comment by Luligabi1** [comment]
Reparing non-vanilla AIOTs is not supported at the moment. However, they shouldn't crash either. I'll check into this in a few minutes!

**Comment by Luligabi1** [comment]
Just uploaded a fix version for this crash. Download version 1.3.1 on CurseForge for the fix (should be available in a few minutes). Thank you for reporting!
