### ISSUE TITLE
Request: Flint Variant

### ISSUE THREAD

**Issue by sarifynna** [Luligabi1/BasicAIOTs#6]
love your mod thank you!

would it be possible to add a flint variant to go along with:
https://www.curseforge.com/minecraft/mc-mods/flinty-tools

if not that's fine, still love the mod as is, just working on a modpack and it would be great to have a flint version too :)

**Comment by Luligabi1** [comment]
I've been busy lately, so I'm not adding new AIOT mod support atm :(
